const employees = [
  {
    id: 1,
    name: "Alice Smith",
    email: "alice.smith@example.com",
    department: "Sales",
  },
  {
    id: 2,
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    department: "Marketing",
  },
  {
    id: 3,
    name: "Charlie Brown",
    email: "charlie.brown@example.com",
    department: "Development",
  },
  {
    id: 4,
    name: "Diana Prince",
    email: "diana.prince@example.com",
    department: "Human Resources",
  },
  {
    id: 5,
    name: "Edward Kenway",
    email: "edward.kenway@example.com",
    department: "Finance",
  },
  {
    id: 6,
    name: "Fiona Gallagher",
    email: "fiona.gallagher@example.com",
    department: "Design",
  },
  {
    id: 7,
    name: "George Martin",
    email: "george.martin@example.com",
    department: "IT Support",
  },
  {
    id: 8,
    name: "Hannah Baker",
    email: "hannah.baker@example.com",
    department: "Customer Service",
  },
  {
    id: 9,
    name: "Ian Malcolm",
    email: "ian.malcolm@example.com",
    department: "Research",
  },
  {
    id: 10,
    name: "Julia Roberts",
    email: "julia.roberts@example.com",
    department: "Administration",
  },
  {
    id: 11,
    name: "Kevin Hart",
    email: "kevin.hart@example.com",
    department: "Sales",
  },
  {
    id: 12,
    name: "Laura Croft",
    email: "laura.croft@example.com",
    department: "Marketing",
  },
  {
    id: 13,
    name: "Michael Scott",
    email: "michael.scott@example.com",
    department: "Development",
  },
  {
    id: 14,
    name: "Nancy Drew",
    email: "nancy.drew@example.com",
    department: "Human Resources",
  },
  {
    id: 15,
    name: "Oscar Wilde",
    email: "oscar.wilde@example.com",
    department: "Finance",
  },
  {
    id: 16,
    name: "Peter Parker",
    email: "peter.parker@example.com",
    department: "Design",
  },
  {
    id: 17,
    name: "Quinn Fabray",
    email: "quinn.fabray@example.com",
    department: "IT Support",
  },
  {
    id: 18,
    name: "Rachel Green",
    email: "rachel.green@example.com",
    department: "Customer Service",
  },
  {
    id: 19,
    name: "Sam Winchester",
    email: "sam.winchester@example.com",
    department: "Research",
  },
  {
    id: 20,
    name: "Tom Hanks",
    email: "tom.hanks@example.com",
    department: "Administration",
  },
  {
    id: 21,
    name: "Ursula K. Le Guin",
    email: "ursula.leguin@example.com",
    department: "Sales",
  },
  {
    id: 22,
    name: "Victor Hugo",
    email: "victor.hugo@example.com",
    department: "Marketing",
  },
  {
    id: 23,
    name: "Winston Churchill",
    email: "winston.churchill@example.com",
    department: "Development",
  },
  {
    id: 24,
    name: "Xena Warrior",
    email: "xena.warrior@example.com",
    department: "Human Resources",
  },
  {
    id: 25,
    name: "Yoda Skywalker",
    email: "yoda.skywalker@example.com",
    department: "Finance",
  },
  {
    id: 26,
    name: "Zach Morris",
    email: "zach.morris@example.com",
    department: "Design",
  },
  {
    id: 27,
    name: "Amelia Earhart",
    email: "amelia.earhart@example.com",
    department: "IT Support",
  },
  {
    id: 28,
    name: "Bruce Wayne",
    email: "bruce.wayne@example.com",
    department: "Customer Service",
  },
  {
    id: 29,
    name: "Clark Kent",
    email: "clark.kent@example.com",
    department: "Research",
  },
  {
    id: 30,
    name: "Darth Vader",
    email: "darth.vader@example.com",
    department: "Administration",
  },
  {
    id: 31,
    name: "Elsa Frozen",
    email: "elsa.frozen@example.com",
    department: "Sales",
  },
  {
    id: 32,
    name: "Frodo Baggins",
    email: "frodo.baggins@example.com",
    department: "Marketing",
  },
  {
    id: 33,
    name: "Gandalf Grey",
    email: "gandalf.grey@example.com",
    department: "Development",
  },
  {
    id: 34,
    name: "Hermione Granger",
    email: "hermione.granger@example.com",
    department: "Human Resources",
  },
  {
    id: 35,
    name: "Icarus Flynn",
    email: "icarus.flynn@example.com",
    department: "Finance",
  },
  {
    id: 36,
    name: "Jack Sparrow",
    email: "jack.sparrow@example.com",
    department: "Design",
  },
  {
    id: 37,
    name: "Katniss Everdeen",
    email: "katniss.everdeen@example.com",
    department: "IT Support",
  },
  {
    id: 38,
    name: "Leonardo DiCaprio",
    email: "leonardo.dicaprio@example.com",
    department: "Customer Service",
  },
  {
    id: 39,
    name: "Marty McFly",
    email: "marty.mcfly@example.com",
    department: "Research",
  },
  {
    id: 40,
    name: "Naruto Uzumaki",
    email: "naruto.uzumaki@example.com",
    department: "Administration",
  },
  {
    id: 41,
    name: "Oprah Winfrey",
    email: "oprah.winfrey@example.com",
    department: "Sales",
  },
  {
    id: 42,
    name: "Pikachu Yellow",
    email: "pikachu.yellow@example.com",
    department: "Marketing",
  },
  {
    id: 43,
    name: "Quasimodo Bell",
    email: "quasimodo.bell@example.com",
    department: "Development",
  },
  {
    id: 44,
    name: "Ragnar Lothbrok",
    email: "ragnar.lothbrok@example.com",
    department: "Human Resources",
  },
  {
    id: 45,
    name: "Sherlock Holmes",
    email: "sherlock.holmes@example.com",
    department: "Finance",
  },
  {
    id: 46,
    name: "Tony Stark",
    email: "tony.stark@example.com",
    department: "Design",
  },
  {
    id: 47,
    name: "Ursula Adams",
    email: "ursula.adams@example.com",
    department: "IT Support",
  },
  {
    id: 48,
    name: "Victor Frankenstein",
    email: "victor.frankenstein@example.com",
    department: "Customer Service",
  },
  {
    id: 49,
    name: "Wolverine Logan",
    email: "wolverine.logan@example.com",
    department: "Research",
  },
  {
    id: 50,
    name: "Xander Harris",
    email: "xander.harris@example.com",
    department: "Administration",
  },
  {
    id: 51,
    name: "Yasmine Bleeth",
    email: "yasmine.bleeth@example.com",
    department: "Sales",
  },
  {
    id: 52,
    name: "Zorro Mask",
    email: "zorro.mask@example.com",
    department: "Marketing",
  },
];

export default employees;
